apiVersion: v1
kind: Pod
metadata: 
  name: liveness-tcp
  namespace: default
spec:
  containers:
  - name: tcp
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:               # 健康检查的方式
        port: 80               # 检查的tcp端口
      initialDelaySeconds: 30  # 表示在第一次执行探针的时候要等待15秒，这样能够确保我们的容器能够有足够的时间启动起来
      timeoutSeconds: 1        # 探测超时时间，默认1秒，最小1秒