apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-demo
spec:
  schedule: "*/1 * * * *"    # 定时任务
  jobTemplate:               # job模板, 类似于Pod模板
    spec:
      template:
        spec:
          restartPolicy: OnFailure  # 重启机制
          containers:
          - name: hello
            image: busybox
            args:
            - "bin/sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"