apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    spec:
      restartPolicy: Never  # job 是一定要设置这个的,
      containers:
      - name: counter
        image: busybox      # Job实际上也是容器的编排,只不过仅运行一次
        command:            # 打印1~9,打印好就退出Pod
        - "bin/sh"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"