apiVersion: v1
kind: Pod
metadata:
  name: secret2-pod
spec:
  containers:
  - name: secret2
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/secrets/password"]
    volumeMounts:
    - name: secrets               # 指定volumes名字
      mountPath: /etc/secrets     # 容器内部路径
  volumes:        
  - name: secrets                 # 定义volumes名字供volumeMounts使用
    secret:                       # 指定要使用的资源类型为secret
     secretName: mysecret         # 使用mysecret挂载到容器中,这样挂载容器中会有2文件,文件名=key名,文件内容等于secret key对应的value
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysecret
#   namespace: default
# type: Opaque
# data:
#   # echo -n "admin" | base64
#   username: YWRtaW4=
#   # echo -n "admin321" | base64
#   password: YWRtaW4zMjE=