# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysecret
#   namespace: default
# type: Opaque
# data:
#   # echo -n "admin" | base64
#   username: YWRtaW4=
#   # echo -n "admin321" | base64
#   password: YWRtaW4zMjE=
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysecret1
#   namespace: default
# type: Opaque
# data:
#   username: YWRtaW4x
#   password: YWRtaW40NTY=
# ---
apiVersion: v1
kind: Pod
metadata:
  name: secret1-pod
spec:
  containers:
  - name: secret1
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:               # 环境变量配置开始,使用envFrom会直接挂载secret的data中key value名字到环境变量中
    - secretRef:
        name: mysecret1    # 指定cm名称
    env:                   # 环境变量配置开始,使用env 可以自定义pod内环境变量名称
    - name: USERNAME       # 定义pod内环境变量名称
      valueFrom:           # 指定环境变量获取方式
        secretKeyRef:
          name: mysecret   # 指定从具体的secret(mysecret)中拿值
          key: username    # key是secret的key名称,挂载到Pod中-->USERNAME=username对应的vaule-->USERNAME=admin
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password