apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 5Gi                    # 大小
  volumeMode: Filesystem            # volume类型
  accessModes:
  - ReadWriteOnce                        # 读取模式
  persistentVolumeReclaimPolicy: Delete  # 删除策略
  storageClassName: local-storage        # 要跟pvc的这个保持一致
  local:                                 # 表明它是一个 Local PV
    path: /data/k8s/localpv              # node02节点上的目录
  nodeAffinity:                          # node 亲和性
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node02
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage         # 跟PV的这个name保持一直
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage                     # StorageClass的名字要跟上面的保持一直
provisioner: kubernetes.io/no-provisioner # 不需要动态来生成 PV
volumeBindingMode: WaitForFirstConsumer   # 延迟绑定机制,否则创建PVC的时候对应的PV就会变成Bound 绑定状态。不符合预期,需要在真正的 Pod 使用的时候才会来做绑定
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-local-pod
spec:
  volumes:
  - name: example-pv-local
    persistentVolumeClaim:      # 使用PVC进行挂载
      claimName: pvc-local      # PVC name
  containers:
  - name: example-pv-local
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: example-pv-local