apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi            # PV容量
  volumeMode: Filesystem    # 存储卷模式
  accessModes:
  - ReadWriteOnce           # 访问模式
  persistentVolumeReclaimPolicy: Recyle # 回收策略
  storageClassName: slow    # SC名字
  mountOptions:
    - haed                  # 挂载选项
    - nfsvers=4.1
  nfs:
    path: /tmp              # nfs目录
    server: 192.168.1.71    # nfs IP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  capacity:
    storage: 5Gi            # PV容量
  accessModes:              # 访问模式
  - ReadWriteOnce           
  persistentVolumeReclaimPolicy: Retain # 回收策略
  volumeMode: Block                     # 存储卷模式
  fc:
    targetWWNs: ["xxxxxxxxx"]           # 
    lun: 0                              # 
    readOnly: false                     #



