apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  # echo -n "admin" | base64
  username: YWRtaW4=
  # echo -n "admin321" | base64
  password: YWRtaW4zMjE=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
  namespace: default
type: Opaque
data:
  username: YWRtaW4x
  password: YWRtaW40NTY=