apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
  # namespace 不受ns限制
rules:
- apiGroups: [""]     
  resources: ["secrets"] 
  verbs: ["get","watch","list"] 