apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets        # 
  namespace: development    # 权限仅在该ns下起作用
subjects:
- kind: User
  name: dave
roleRef:                       # 角色绑定信息 
  kind: ClusterRole            # 绑定的对象是角色,也可以是集群角色
  name: secret-reader          # 绑定的Role name
  apiGroup: rbac.authorization.k8s.io  # 
# 