apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]     # 空字符串,表示 Core API Group
  resources: ["pods"] # 这个Role只可以操作Pod,操作方式在下面的verbs[]
  verbs: ["get","watch","list"] 