apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-appfile
  namespace: default
data:
  key-serverxml: |
    abcdefg
  key-loggingproperties: |
    123456
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
  namespace: default
spec:
  containers:
  - name: cp-test-app
    image: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: serverxml         # 上面Volume名字
      mountPath: /configfiles # 容器内部目录
  volumes:
  - name: serverxml       # 定义volume的名字,容器中volumeMount的时候需要指定这个名字
    configMap:
      name: cm-appfile     # cm name
      items:               # 遍历cm中的data属性,一个个自定义文件名挂载
      - key: key-serverxml # key=cm中key-serverxml的名字
        path: server.xml   # 挂载的名字自定义为server.xml 
      - key: key-loggingproperties  # 同上
        path: logging.properties    # 同上
