apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  password: YWRtaW4K
  username: YWRtaW4K
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-app
  namespace: default
spec:
  containers:
  - name: secret-test-app
    image: busybox
    command: 
    - sleep
    - 3600s
    volumeMounts:
    - name: mysecret          # Volume名字
      mountPath: /tmp         # 容器内部目录
  volumes:
  - name: mysecret       # 定义volume的名字,容器中volumeMount的时候需要指定这个名字
    secret:
      secretName: mysecret
     
      
