apiVersion: v1
kind: Pod
metadata:
  name: dapi-vol
  labels:
    zone: us-est-coast
    cluster: test-cluster
    rack: rack-22
  annotations:
    build: tzh
    builder: tzh666
  namespace: default
spec:
  containers:
  - name: client-container
    image: busybox
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: podinfo           # volume名称
      mountPath: /etc/podinfo # 容器内路径
  volumes:                  
    - name: podinfo           # volume名称
      downwardAPI:            # 在Pod的volumes字段中使用downwardAPI的方法,通过fieldRef设置引用pod的元数据信息,将其设置到volume中的items中
        items:
          - path: "lables"                       # 挂载到Pod的file name
            fieldRef:
              fieldPath: metadata.labels         # pod中的labels列表
          - path: "annotations"                  # 挂载到Pod的file name
            fieldRef:
              fieldPath: metadata.annotations    # pod的annotations列表
# 验证结果
# [root@master01 downward-API]# kubectl exec -it  dapi-vol  -- cat /etc/podinfo/lables
# cluster="test-cluster"
# rack="rack-22"